

version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - data/db:/var/lib/postgresql/data

  web:
    container_name: web
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
      
  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - static_volume:/code/static
  #   links:
  #     - web:web

volumes:
  static_volume:
