version: '3'
services:
  web:
    container_name: web
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "80:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      
volumes:
  static_volume:
