version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      -   db_data:/var/lib/postgresql/data
    networks:
      - djnetwork
  web:
    container_name: web
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
    networks:
      - djnetwork
   
  react:
    image: mdnazmulhossain/react-123
    ports:
      - "80:3000"
    depends_on:
      - web
    networks:
      - djnetwork
  
volumes:
  static_volume:
  db_data:

networks:
  djnetwork:
    driver: bridge