version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      -   db_data:/var/lib/postgresql/data
    networks:
      - djnetwork


  backend:
    container_name: backend
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
    networks:
      - djnetwork
   
  frontend:
    image: mdnazmulhossain/react-123
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - djnetwork
  
volumes:
  static_volume:
  db_data:

networks:
  djnetwork:
    driver: bridge