# Generated by Django 3.2 on 2022-08-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_is_archived'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myphotos',
        ),
    ]
