# Generated by Django 3.2 on 2022-08-13 09:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_myphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
